### PR TITLE
exposed functions don't need to be unsafe

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b5d9ae5 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b5d9ae5 with merge b5d9ae5...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/cu/builds/131779683)

**Pull request merged**
