### PR TITLE
don't pass -Wl,-( and -Wl,-) to the linker

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 097b2e9 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 097b2e9 with merge 2fd547f...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cu/builds/160329101)
Approved by: japaric
Pushing 2fd547f25bb7bb019d92e33b37bd47d084682161 to master...

**Pull request merged**
