### PR TITLE
tweak linker scripts

### PR DESCRIPTION
**Pull request by japaric**
to resemble the current state of the Copper book

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e30f847 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e30f847 with merge d8ce47e...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/japaric/cu/builds/143224625)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:bulb: This pull request was already approved, no need to approve it again.
- This pull request previously failed. You should add more commits to fix the bug, or use `retry` to trigger a build again.

**Comment by homunkulus** [comment]
:pushpin: Commit e30f847 has been approved by `japaric`

**Comment by japaric** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit e30f847 with merge 57bedea...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/japaric/cu/builds/143480016)

**Comment by japaric** [comment]
@homunkulus rerty

**Comment by japaric** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit e30f847 with merge 832ea53...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/japaric/cu/builds/143480579)

**Comment by japaric** [comment]
@homunkulus retry

**Comment by japaric** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit e30f847 with merge bf478ec...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/cu/builds/143610748)

**Pull request merged**
