### PR TITLE
enable lto

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0325c51 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0325c51 with merge 0325c51...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/cu/builds/131797942)

**Pull request merged**
