### PR TITLE
remove --gc-sections for the target specification file

### PR DESCRIPTION
**Pull request by japaric**
this flag is already pass to the linker invocation

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2104cbe has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2104cbe with merge 2995e7f...

**Comment by japaric** [comment]
@homunkulus r-

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2104cbe has been approved by `japaric`

**Comment by japaric** [comment]
@homunkulus retry force clean

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d2eb753 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d2eb753 with merge 0161648...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/cu/builds/126674424)

**Pull request merged**
