### PR TITLE
update linker scripts

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 900728a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 900728a with merge 900728a...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/cu/builds/127305259)

**Pull request merged**
