### PR TITLE
ci: update docker image

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2fcc1de has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2fcc1de with merge c5e072a...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/cu/builds/129321443)

**Pull request merged**
