### PR TITLE
ci: use newer docker image

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@dynomu: r+

**Comment by dynomu** [comment]
:pushpin: Commit b5dfd1d has been approved by `japaric`

**Comment by dynomu** [comment]
:hourglass: Testing commit b5dfd1d with merge 7cd4657...

**Comment by dynomu** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/cu/builds/126143410)

**Pull request merged**
