### PR TITLE
directly set the initial SP value in the linker script

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4df5a75 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4df5a75 with merge 4df5a75...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/cu/builds/132456928)

**Pull request merged**
