### PR TITLE
use core::ptr instead of core::intrinsics

### PR DESCRIPTION
**Pull request by japaric**
the volatile load/store stuff has been stabilized! Yay, one less feature
gate.

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 30dbfc9 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 30dbfc9 with merge 30dbfc9...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/cu/builds/131847136)

**Pull request merged**
