### PR TITLE
ci: use a newer docker image

### PR DESCRIPTION
**Pull request by japaric**
now we don't need to set AR and CC env variables

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d632c42 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d632c42 with merge d632c42...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/cu/builds/128594289)

**Pull request merged**
