### PR TITLE
ci: check that all the generated ELF files have an entry point

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 257a2ef has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 257a2ef with merge 257a2ef...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/japaric/cu/builds/132462910)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 49db6d8 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 49db6d8 with merge 49db6d8...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/cu/builds/132543339)

**Pull request merged**
