### PR TITLE
use the compiler-rt crate

### PR DESCRIPTION
**Pull request by japaric**
it contains all the intrinsics we will ever need. Previously we were rolling
our own with just the __aeabi_memcpy\* symbols.

Note: The -Wl,-( and -Wl,-) are needed to avoid ordering problems at linking
time.

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8259df2 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8259df2 with merge 8259df2...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/japaric/cu/builds/127315742)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 84e9381 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 84e9381 with merge 84e9381...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/japaric/cu/builds/127317051)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8eb871b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8eb871b with merge 8eb871b...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/japaric/cu/builds/127319246)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e6ce497 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e6ce497 with merge e6ce497...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/cu/builds/127323248)

**Pull request merged**
