### PR TITLE
TIL: #![no_main]

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 38d8f03 with merge 38d8f03...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/japaric/cu/builds/129321708)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0180c4f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0180c4f with merge 0180c4f...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/cu/builds/131808804)

**Pull request merged**
