### PR TITLE
strip build-id in the linker script

### PR DESCRIPTION
**Pull request by japaric**
instead of disabling it via a linker flag

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit dd962f0 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit dd962f0 with merge b2a6309...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/cu/builds/126672435)

**Comment by japaric** [comment]
:tada:

**Pull request merged**
