### PR TITLE
rename target from stm32f100 to thumbv7m-none-eabi

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 44094c4 has been approved by `japaric`

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4dfd9f9 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4dfd9f9 with merge 3682168...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/cu/builds/126760334)

**Pull request merged**
